# Generated by Django 3.0.2 on 2020-01-18 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pinball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 18, 14, 59, 3, 548803, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
